# Generated by Django 5.0.6 on 2024-05-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
