# Generated by Django 5.0.6 on 2024-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_adress_customerprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(max_length=13),
        ),
    ]
