# Generated by Django 5.0.6 on 2024-05-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_customerprofile_address_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='proffesion',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_customer',
        ),
    ]
