# Generated by Django 5.0.6 on 2024-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_proffesion_staffprofile_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
