# Generated by Django 5.0.6 on 2024-05-11 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='modals',
        ),
        migrations.AddField(
            model_name='toy',
            name='modals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.toymodal'),
            preserve_default=False,
        ),
    ]
