# Generated by Django 5.0.6 on 2024-05-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_toy_modals_toy_modals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='modal',
        ),
    ]
