# Generated by Django 5.0.6 on 2024-05-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_customerprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='age',
        ),
    ]
